name: traccar_client
description: "Cypher Track"
publish_to: 'none'
version: 1.0.2+162

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  traccar_client_sdk: 1.1.1
  shared_preferences: ^2.5.5
  shared_preferences_android: ^2.4.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
  generate: true
